
#Settings for Inventory HUD
[inventoryhud]
	#Inventory HUD mini mode
	invMini = true
	#Inventory HUD vertical mode
	invVert = false
	#Inventory HUD alpha
	#Range: 0 ~ 100
	invAlpha = 0
	#Toggle on by default
	byDefault = true
	#Animate recently picked up items
	animatedInv = true
	#Hide background if inventory is empty
	hideBackground = true

#Settings for ArmorStatus HUD
[armorhud]
	#Is Armor Damage HUD enabled
	ArmorDamage = true
	#Hide if durability is above this (in percentage):
	#Range: 0 ~ 100
	armAbove = 100
	#Show/Hide armor
	showArmor = true
	#Show/Hide armor
	showMain = false
	#Show/Hide armor
	showOff = false
	#Show/Hide armor
	showArrows = false
	#Show/Hide armor
	showInv = false
	#Armor HUD durability view (PERCENTAGE, DAMAGE, DAMAGE LEFT)
	#Allowed Values: PERCENTAGE, DAMAGE, DAMAGE_LEFT, OFF
	armView = "OFF"
	#Show item durability bar
	armBars = true
	#Move all items at once or each one
	moveAll = false
	#Show/Hide empty slot icon
	showEmpty = false
	#Show overall count of items in main/off hand
	showCount = true
	#ArmorHUD scale in persentage from 50 to 150
	#Range: 50 ~ 150
	armScale = 100

#Settings for Potions HUD
[potionshud]
	#Is Potions HUD enabled
	Potions = true
	#Potion HUD alpha
	#Range: 0 ~ 100
	potAlpha = 100
	#Potion HUD gap
	#Range: -5 ~ 5
	potGap = 0
	#Potion HUD mini mode
	potMini = true
	#Potion HUD horizontal mode
	potHor = false
	#Full bar duration
	#Range: > 1
	barDuration = 300

#DONT TOUCH THESE FIELDS!
[positions]
	#Inventory HUD vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	invValign = "BOTTOM"
	#Inventory HUD horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	invHalign = "RIGHT"
	#Inventory HUD position (X)
	#Range: -9999 ~ 9999
	xPos = 120
	#Inventory HUD position (Y)
	#Range: -9999 ~ 9999
	yPos = 41
	#Armor HUD vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	armValign = "BOTTOM"
	#Armor HUD horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	armHalign = "MIDDLE"
	#Armor HUD position (X)
	#Range: -9999 ~ 9999
	xArmPos = -138
	#Armor HUD position (Y)
	#Range: -9999 ~ 9999
	yArmPos = 70
	#Potion HUD vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	potValign = "TOP"
	#Potion HUD horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	potHalign = "LEFT"
	#Potion HUD position (X)
	#Range: -9999 ~ 9999
	xPotionPos = 34
	#Potion HUD position (Y)
	#Range: -9999 ~ 9999
	yPotionPos = 12
	#Helmet position (X)
	#Range: -9999 ~ 9999
	helmPosX = -106
	#Helmet position (Y)
	#Range: -9999 ~ 9999
	helmPosY = 39
	#Chestplate position (X)
	#Range: -9999 ~ 9999
	chestPosX = -106
	#Chestplate position (Y)
	#Range: -9999 ~ 9999
	chestPosY = 21
	#Leggings position (X)
	#Range: -9999 ~ 9999
	legPosX = -126
	#Leggings position (Y)
	#Range: -9999 ~ 9999
	legPosY = 39
	#Boots position (X)
	#Range: -9999 ~ 9999
	bootPosX = -126
	#Boots position (Y)
	#Range: -9999 ~ 9999
	bootPosY = 21
	#MainHand position (X)
	#Range: -9999 ~ 9999
	mainPosX = 44
	#MainHand position (Y)
	#Range: -9999 ~ 9999
	mainPosY = 70
	#OffHand position (X)
	#Range: -9999 ~ 9999
	offPosX = 64
	#OffHand position (Y)
	#Range: -9999 ~ 9999
	offPosY = 68
	#Arrows position (X)
	#Range: -9999 ~ 9999
	arrPosX = 110
	#Arrows position (Y)
	#Range: -9999 ~ 9999
	arrPosY = 69
	#InvIcon position (X)
	#Range: -9999 ~ 9999
	invPosX = 87
	#InvIcon position (Y)
	#Range: -9999 ~ 9999
	invPosY = 67
	#Helmet horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	helmHal = "MIDDLE"
	#Helmet vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	helmVal = "BOTTOM"
	#Chestplate horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	chestHal = "MIDDLE"
	#Chestplate vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	chestVal = "BOTTOM"
	#Leggings horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	legHal = "MIDDLE"
	#Leggings vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	legVal = "BOTTOM"
	#Boots horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	bootHal = "MIDDLE"
	#Boots vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	bootVal = "BOTTOM"
	#MainHand horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	mainHal = "RIGHT"
	#MainHand vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	mainVal = "BOTTOM"
	#OffHand horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	offHal = "RIGHT"
	#OffHand vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	offVal = "BOTTOM"
	#Arrows horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	arrHal = "RIGHT"
	#Arrows vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	arrVal = "BOTTOM"
	#InvIcon horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	invHal = "RIGHT"
	#InvIcon vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	invVal = "BOTTOM"

